-- CreateTable
CREATE TABLE "Patient" (
    "id" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "gender" TEXT,
    "birthDate" TIMESTAMP(3),
    "phone1" TEXT,
    "phone2" TEXT,
    "email" TEXT,
    "homeDistanceKm" DOUBLE PRECISION,
    "educationLevel" TEXT,
    "occupation" TEXT,
    "currentActivity" TEXT,
    "referringCaregiver" TEXT,
    "mhd" TEXT,
    "followUpToDo" BOOLEAN,
    "theraflow" TEXT,
    "notes" TEXT,
    "details" TEXT,
    "medicalDiagnosis" TEXT,
    "entryDate" TIMESTAMP(3),
    "careMode" TEXT,
    "orientation" TEXT,
    "etpDecision" TEXT,
    "programType" TEXT,
    "nonInclusionDetails" TEXT,
    "customContentDetails" TEXT,
    "goal" TEXT,
    "exitDate" TIMESTAMP(3),
    "stopReason" TEXT,
    "etpFinalOutcome" TEXT,
    "offers" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Patient_pkey" PRIMARY KEY ("id")
);
