/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as PatientIndexImport } from './routes/patient/index'
import { Route as SettingsUserImport } from './routes/settings/user'
import { Route as SettingsSoignantImport } from './routes/settings/soignant'
import { Route as SettingsPlanningImport } from './routes/settings/planning'
import { Route as PatientPatientIDImport } from './routes/patient/$patientID'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PatientIndexRoute = PatientIndexImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsUserRoute = SettingsUserImport.update({
  id: '/settings/user',
  path: '/settings/user',
  getParentRoute: () => rootRoute,
} as any)

const SettingsSoignantRoute = SettingsSoignantImport.update({
  id: '/settings/soignant',
  path: '/settings/soignant',
  getParentRoute: () => rootRoute,
} as any)

const SettingsPlanningRoute = SettingsPlanningImport.update({
  id: '/settings/planning',
  path: '/settings/planning',
  getParentRoute: () => rootRoute,
} as any)

const PatientPatientIDRoute = PatientPatientIDImport.update({
  id: '/patient/$patientID',
  path: '/patient/$patientID',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/patient/$patientID': {
      id: '/patient/$patientID'
      path: '/patient/$patientID'
      fullPath: '/patient/$patientID'
      preLoaderRoute: typeof PatientPatientIDImport
      parentRoute: typeof rootRoute
    }
    '/settings/planning': {
      id: '/settings/planning'
      path: '/settings/planning'
      fullPath: '/settings/planning'
      preLoaderRoute: typeof SettingsPlanningImport
      parentRoute: typeof rootRoute
    }
    '/settings/soignant': {
      id: '/settings/soignant'
      path: '/settings/soignant'
      fullPath: '/settings/soignant'
      preLoaderRoute: typeof SettingsSoignantImport
      parentRoute: typeof rootRoute
    }
    '/settings/user': {
      id: '/settings/user'
      path: '/settings/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof SettingsUserImport
      parentRoute: typeof rootRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/patient/$patientID': typeof PatientPatientIDRoute
  '/settings/planning': typeof SettingsPlanningRoute
  '/settings/soignant': typeof SettingsSoignantRoute
  '/settings/user': typeof SettingsUserRoute
  '/patient': typeof PatientIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/patient/$patientID': typeof PatientPatientIDRoute
  '/settings/planning': typeof SettingsPlanningRoute
  '/settings/soignant': typeof SettingsSoignantRoute
  '/settings/user': typeof SettingsUserRoute
  '/patient': typeof PatientIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/patient/$patientID': typeof PatientPatientIDRoute
  '/settings/planning': typeof SettingsPlanningRoute
  '/settings/soignant': typeof SettingsSoignantRoute
  '/settings/user': typeof SettingsUserRoute
  '/patient/': typeof PatientIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/patient/$patientID'
    | '/settings/planning'
    | '/settings/soignant'
    | '/settings/user'
    | '/patient'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/patient/$patientID'
    | '/settings/planning'
    | '/settings/soignant'
    | '/settings/user'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/patient/$patientID'
    | '/settings/planning'
    | '/settings/soignant'
    | '/settings/user'
    | '/patient/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AuthLoginRoute: typeof AuthLoginRoute
  PatientPatientIDRoute: typeof PatientPatientIDRoute
  SettingsPlanningRoute: typeof SettingsPlanningRoute
  SettingsSoignantRoute: typeof SettingsSoignantRoute
  SettingsUserRoute: typeof SettingsUserRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AuthLoginRoute: AuthLoginRoute,
  PatientPatientIDRoute: PatientPatientIDRoute,
  SettingsPlanningRoute: SettingsPlanningRoute,
  SettingsSoignantRoute: SettingsSoignantRoute,
  SettingsUserRoute: SettingsUserRoute,
  PatientIndexRoute: PatientIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/auth/login",
        "/patient/$patientID",
        "/settings/planning",
        "/settings/soignant",
        "/settings/user",
        "/patient/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/patient/$patientID": {
      "filePath": "patient/$patientID.tsx"
    },
    "/settings/planning": {
      "filePath": "settings/planning.tsx"
    },
    "/settings/soignant": {
      "filePath": "settings/soignant.tsx"
    },
    "/settings/user": {
      "filePath": "settings/user.tsx"
    },
    "/patient/": {
      "filePath": "patient/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
