/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PendingImport } from './routes/pending'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthAccessLinkImport } from './routes/auth/access-link'
import { Route as AuthenticatedSuperAdminImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedSuiviImport } from './routes/_authenticated/suivi'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChooseContextImport } from './routes/_authenticated/choose-context'
import { Route as AuthenticatedAgendaImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedSuperAdminIndexImport } from './routes/_authenticated/super-admin/index'
import { Route as AuthenticatedPatientIndexImport } from './routes/_authenticated/patient/index'
import { Route as AuthenticatedUserSettingsImport } from './routes/_authenticated/user/settings'
import { Route as AuthenticatedSuperAdminUsersImport } from './routes/_authenticated/super-admin/users'
import { Route as AuthenticatedSuperAdminAccessLogImport } from './routes/_authenticated/super-admin/access-log'
import { Route as AuthenticatedSuperAdminEstablishmentIdImport } from './routes/_authenticated/super-admin/$establishmentId'
import { Route as AuthenticatedSettingsUserImport } from './routes/_authenticated/settings/user'
import { Route as AuthenticatedSettingsThematicImport } from './routes/_authenticated/settings/thematic'
import { Route as AuthenticatedSettingsSoignantImport } from './routes/_authenticated/settings/soignant'
import { Route as AuthenticatedSettingsPlanningImport } from './routes/_authenticated/settings/planning'
import { Route as AuthenticatedSettingsLocationImport } from './routes/_authenticated/settings/location'
import { Route as AuthenticatedSettingsDiagnosticTemplateImport } from './routes/_authenticated/settings/diagnostic-template'
import { Route as AuthenticatedSettingsActivityLogImport } from './routes/_authenticated/settings/activity-log'
import { Route as AuthenticatedPatientPatientIDImport } from './routes/_authenticated/patient/$patientID'
import { Route as AuthenticatedEEstablishmentIdAdminImport } from './routes/_authenticated/e/$establishmentId/admin'
import { Route as AuthenticatedEEstablishmentIdSServiceIdImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId'
import { Route as AuthenticatedEEstablishmentIdAdminSoignantsImport } from './routes/_authenticated/e/$establishmentId/admin/soignants'
import { Route as AuthenticatedEEstablishmentIdAdminServicesImport } from './routes/_authenticated/e/$establishmentId/admin/services'
import { Route as AuthenticatedEEstablishmentIdAdminMembersImport } from './routes/_authenticated/e/$establishmentId/admin/members'
import { Route as AuthenticatedEEstablishmentIdAdminLocationsImport } from './routes/_authenticated/e/$establishmentId/admin/locations'
import { Route as AuthenticatedEEstablishmentIdAdminGrantsImport } from './routes/_authenticated/e/$establishmentId/admin/grants'
import { Route as AuthenticatedEEstablishmentIdAdminActivityLogImport } from './routes/_authenticated/e/$establishmentId/admin/activity-log'
import { Route as AuthenticatedEEstablishmentIdSServiceIdIndexImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/index'
import { Route as AuthenticatedEEstablishmentIdSServiceIdSuiviImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/suivi'
import { Route as AuthenticatedEEstablishmentIdSServiceIdSoignantImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/soignant'
import { Route as AuthenticatedEEstablishmentIdSServiceIdLocationImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/location'
import { Route as AuthenticatedEEstablishmentIdSServiceIdDashboardImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/dashboard'
import { Route as AuthenticatedEEstablishmentIdSServiceIdAgendaImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/agenda'
import { Route as AuthenticatedEEstablishmentIdSServiceIdActivityLogImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/activity-log'
import { Route as AuthenticatedEEstablishmentIdSServiceIdSettingsImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/_settings'
import { Route as AuthenticatedEEstablishmentIdSServiceIdPatientIndexImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/patient/index'
import { Route as AuthenticatedEEstablishmentIdSServiceIdSettingsThematicImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/_settings/thematic'
import { Route as AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/_settings/planning'
import { Route as AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/_settings/diagnostic-template'
import { Route as AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/index'
import { Route as AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesImport } from './routes/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/acces'

// Create/Update Routes

const PendingRoute = PendingImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthAccessLinkRoute = AuthAccessLinkImport.update({
  id: '/auth/access-link',
  path: '/auth/access-link',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSuiviRoute = AuthenticatedSuiviImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedChooseContextRoute = AuthenticatedChooseContextImport.update(
  {
    id: '/choose-context',
    path: '/choose-context',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedAgendaRoute = AuthenticatedAgendaImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)

const AuthenticatedPatientIndexRoute = AuthenticatedPatientIndexImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedUserSettingsRoute = AuthenticatedUserSettingsImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSuperAdminUsersRoute =
  AuthenticatedSuperAdminUsersImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)

const AuthenticatedSuperAdminAccessLogRoute =
  AuthenticatedSuperAdminAccessLogImport.update({
    id: '/access-log',
    path: '/access-log',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)

const AuthenticatedSuperAdminEstablishmentIdRoute =
  AuthenticatedSuperAdminEstablishmentIdImport.update({
    id: '/$establishmentId',
    path: '/$establishmentId',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)

const AuthenticatedSettingsUserRoute = AuthenticatedSettingsUserImport.update({
  id: '/settings/user',
  path: '/settings/user',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedSettingsThematicRoute =
  AuthenticatedSettingsThematicImport.update({
    id: '/settings/thematic',
    path: '/settings/thematic',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSettingsSoignantRoute =
  AuthenticatedSettingsSoignantImport.update({
    id: '/settings/soignant',
    path: '/settings/soignant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSettingsPlanningRoute =
  AuthenticatedSettingsPlanningImport.update({
    id: '/settings/planning',
    path: '/settings/planning',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSettingsLocationRoute =
  AuthenticatedSettingsLocationImport.update({
    id: '/settings/location',
    path: '/settings/location',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSettingsDiagnosticTemplateRoute =
  AuthenticatedSettingsDiagnosticTemplateImport.update({
    id: '/settings/diagnostic-template',
    path: '/settings/diagnostic-template',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedSettingsActivityLogRoute =
  AuthenticatedSettingsActivityLogImport.update({
    id: '/settings/activity-log',
    path: '/settings/activity-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedPatientPatientIDRoute =
  AuthenticatedPatientPatientIDImport.update({
    id: '/patient/$patientID',
    path: '/patient/$patientID',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedEEstablishmentIdAdminRoute =
  AuthenticatedEEstablishmentIdAdminImport.update({
    id: '/e/$establishmentId/admin',
    path: '/e/$establishmentId/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdRoute =
  AuthenticatedEEstablishmentIdSServiceIdImport.update({
    id: '/e/$establishmentId/s/$serviceId',
    path: '/e/$establishmentId/s/$serviceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedEEstablishmentIdAdminSoignantsRoute =
  AuthenticatedEEstablishmentIdAdminSoignantsImport.update({
    id: '/soignants',
    path: '/soignants',
    getParentRoute: () => AuthenticatedEEstablishmentIdAdminRoute,
  } as any)

const AuthenticatedEEstablishmentIdAdminServicesRoute =
  AuthenticatedEEstablishmentIdAdminServicesImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedEEstablishmentIdAdminRoute,
  } as any)

const AuthenticatedEEstablishmentIdAdminMembersRoute =
  AuthenticatedEEstablishmentIdAdminMembersImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedEEstablishmentIdAdminRoute,
  } as any)

const AuthenticatedEEstablishmentIdAdminLocationsRoute =
  AuthenticatedEEstablishmentIdAdminLocationsImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedEEstablishmentIdAdminRoute,
  } as any)

const AuthenticatedEEstablishmentIdAdminGrantsRoute =
  AuthenticatedEEstablishmentIdAdminGrantsImport.update({
    id: '/grants',
    path: '/grants',
    getParentRoute: () => AuthenticatedEEstablishmentIdAdminRoute,
  } as any)

const AuthenticatedEEstablishmentIdAdminActivityLogRoute =
  AuthenticatedEEstablishmentIdAdminActivityLogImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedEEstablishmentIdAdminRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdIndexRoute =
  AuthenticatedEEstablishmentIdSServiceIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdSuiviRoute =
  AuthenticatedEEstablishmentIdSServiceIdSuiviImport.update({
    id: '/suivi',
    path: '/suivi',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdSoignantRoute =
  AuthenticatedEEstablishmentIdSServiceIdSoignantImport.update({
    id: '/soignant',
    path: '/soignant',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdLocationRoute =
  AuthenticatedEEstablishmentIdSServiceIdLocationImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdDashboardRoute =
  AuthenticatedEEstablishmentIdSServiceIdDashboardImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdAgendaRoute =
  AuthenticatedEEstablishmentIdSServiceIdAgendaImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdActivityLogRoute =
  AuthenticatedEEstablishmentIdSServiceIdActivityLogImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdSettingsRoute =
  AuthenticatedEEstablishmentIdSServiceIdSettingsImport.update({
    id: '/_settings',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdPatientIndexRoute =
  AuthenticatedEEstablishmentIdSServiceIdPatientIndexImport.update({
    id: '/patient/',
    path: '/patient/',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdSettingsThematicRoute =
  AuthenticatedEEstablishmentIdSServiceIdSettingsThematicImport.update({
    id: '/thematic',
    path: '/thematic',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdSettingsRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningRoute =
  AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningImport.update({
    id: '/planning',
    path: '/planning',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdSettingsRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateRoute =
  AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateImport.update(
    {
      id: '/diagnostic-template',
      path: '/diagnostic-template',
      getParentRoute: () =>
        AuthenticatedEEstablishmentIdSServiceIdSettingsRoute,
    } as any,
  )

const AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexRoute =
  AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexImport.update({
    id: '/patient/$patientID/',
    path: '/patient/$patientID/',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

const AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesRoute =
  AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesImport.update({
    id: '/patient/$patientID/acces',
    path: '/patient/$patientID/acces',
    getParentRoute: () => AuthenticatedEEstablishmentIdSServiceIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/choose-context': {
      id: '/_authenticated/choose-context'
      path: '/choose-context'
      fullPath: '/choose-context'
      preLoaderRoute: typeof AuthenticatedChooseContextImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/suivi': {
      id: '/_authenticated/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof AuthenticatedSuiviImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth/access-link': {
      id: '/auth/access-link'
      path: '/auth/access-link'
      fullPath: '/auth/access-link'
      preLoaderRoute: typeof AuthAccessLinkImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/patient/$patientID': {
      id: '/_authenticated/patient/$patientID'
      path: '/patient/$patientID'
      fullPath: '/patient/$patientID'
      preLoaderRoute: typeof AuthenticatedPatientPatientIDImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/activity-log': {
      id: '/_authenticated/settings/activity-log'
      path: '/settings/activity-log'
      fullPath: '/settings/activity-log'
      preLoaderRoute: typeof AuthenticatedSettingsActivityLogImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/diagnostic-template': {
      id: '/_authenticated/settings/diagnostic-template'
      path: '/settings/diagnostic-template'
      fullPath: '/settings/diagnostic-template'
      preLoaderRoute: typeof AuthenticatedSettingsDiagnosticTemplateImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/location': {
      id: '/_authenticated/settings/location'
      path: '/settings/location'
      fullPath: '/settings/location'
      preLoaderRoute: typeof AuthenticatedSettingsLocationImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/planning': {
      id: '/_authenticated/settings/planning'
      path: '/settings/planning'
      fullPath: '/settings/planning'
      preLoaderRoute: typeof AuthenticatedSettingsPlanningImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/soignant': {
      id: '/_authenticated/settings/soignant'
      path: '/settings/soignant'
      fullPath: '/settings/soignant'
      preLoaderRoute: typeof AuthenticatedSettingsSoignantImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/thematic': {
      id: '/_authenticated/settings/thematic'
      path: '/settings/thematic'
      fullPath: '/settings/thematic'
      preLoaderRoute: typeof AuthenticatedSettingsThematicImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/settings/user': {
      id: '/_authenticated/settings/user'
      path: '/settings/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof AuthenticatedSettingsUserImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/super-admin/$establishmentId': {
      id: '/_authenticated/super-admin/$establishmentId'
      path: '/$establishmentId'
      fullPath: '/super-admin/$establishmentId'
      preLoaderRoute: typeof AuthenticatedSuperAdminEstablishmentIdImport
      parentRoute: typeof AuthenticatedSuperAdminImport
    }
    '/_authenticated/super-admin/access-log': {
      id: '/_authenticated/super-admin/access-log'
      path: '/access-log'
      fullPath: '/super-admin/access-log'
      preLoaderRoute: typeof AuthenticatedSuperAdminAccessLogImport
      parentRoute: typeof AuthenticatedSuperAdminImport
    }
    '/_authenticated/super-admin/users': {
      id: '/_authenticated/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof AuthenticatedSuperAdminUsersImport
      parentRoute: typeof AuthenticatedSuperAdminImport
    }
    '/_authenticated/user/settings': {
      id: '/_authenticated/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof AuthenticatedUserSettingsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/patient/': {
      id: '/_authenticated/patient/'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexImport
      parentRoute: typeof AuthenticatedSuperAdminImport
    }
    '/_authenticated/e/$establishmentId/admin': {
      id: '/_authenticated/e/$establishmentId/admin'
      path: '/e/$establishmentId/admin'
      fullPath: '/e/$establishmentId/admin'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdAdminImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/e/$establishmentId/admin/activity-log': {
      id: '/_authenticated/e/$establishmentId/admin/activity-log'
      path: '/activity-log'
      fullPath: '/e/$establishmentId/admin/activity-log'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdAdminActivityLogImport
      parentRoute: typeof AuthenticatedEEstablishmentIdAdminImport
    }
    '/_authenticated/e/$establishmentId/admin/grants': {
      id: '/_authenticated/e/$establishmentId/admin/grants'
      path: '/grants'
      fullPath: '/e/$establishmentId/admin/grants'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdAdminGrantsImport
      parentRoute: typeof AuthenticatedEEstablishmentIdAdminImport
    }
    '/_authenticated/e/$establishmentId/admin/locations': {
      id: '/_authenticated/e/$establishmentId/admin/locations'
      path: '/locations'
      fullPath: '/e/$establishmentId/admin/locations'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdAdminLocationsImport
      parentRoute: typeof AuthenticatedEEstablishmentIdAdminImport
    }
    '/_authenticated/e/$establishmentId/admin/members': {
      id: '/_authenticated/e/$establishmentId/admin/members'
      path: '/members'
      fullPath: '/e/$establishmentId/admin/members'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdAdminMembersImport
      parentRoute: typeof AuthenticatedEEstablishmentIdAdminImport
    }
    '/_authenticated/e/$establishmentId/admin/services': {
      id: '/_authenticated/e/$establishmentId/admin/services'
      path: '/services'
      fullPath: '/e/$establishmentId/admin/services'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdAdminServicesImport
      parentRoute: typeof AuthenticatedEEstablishmentIdAdminImport
    }
    '/_authenticated/e/$establishmentId/admin/soignants': {
      id: '/_authenticated/e/$establishmentId/admin/soignants'
      path: '/soignants'
      fullPath: '/e/$establishmentId/admin/soignants'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdAdminSoignantsImport
      parentRoute: typeof AuthenticatedEEstablishmentIdAdminImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId'
      path: '/e/$establishmentId/s/$serviceId'
      fullPath: '/e/$establishmentId/s/$serviceId'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/_settings': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/_settings'
      path: ''
      fullPath: '/e/$establishmentId/s/$serviceId'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/activity-log': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/activity-log'
      path: '/activity-log'
      fullPath: '/e/$establishmentId/s/$serviceId/activity-log'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdActivityLogImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/agenda': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/agenda'
      path: '/agenda'
      fullPath: '/e/$establishmentId/s/$serviceId/agenda'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdAgendaImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/dashboard': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/dashboard'
      path: '/dashboard'
      fullPath: '/e/$establishmentId/s/$serviceId/dashboard'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdDashboardImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/location': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/location'
      path: '/location'
      fullPath: '/e/$establishmentId/s/$serviceId/location'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdLocationImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/soignant': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/soignant'
      path: '/soignant'
      fullPath: '/e/$establishmentId/s/$serviceId/soignant'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSoignantImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/suivi': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/suivi'
      path: '/suivi'
      fullPath: '/e/$establishmentId/s/$serviceId/suivi'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSuiviImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/'
      path: '/'
      fullPath: '/e/$establishmentId/s/$serviceId/'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdIndexImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/_settings/diagnostic-template': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/_settings/diagnostic-template'
      path: '/diagnostic-template'
      fullPath: '/e/$establishmentId/s/$serviceId/diagnostic-template'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/_settings/planning': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/_settings/planning'
      path: '/planning'
      fullPath: '/e/$establishmentId/s/$serviceId/planning'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/_settings/thematic': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/_settings/thematic'
      path: '/thematic'
      fullPath: '/e/$establishmentId/s/$serviceId/thematic'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsThematicImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/patient/': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/patient/'
      path: '/patient'
      fullPath: '/e/$establishmentId/s/$serviceId/patient'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdPatientIndexImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/acces': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/acces'
      path: '/patient/$patientID/acces'
      fullPath: '/e/$establishmentId/s/$serviceId/patient/$patientID/acces'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
    '/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/': {
      id: '/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/'
      path: '/patient/$patientID'
      fullPath: '/e/$establishmentId/s/$serviceId/patient/$patientID'
      preLoaderRoute: typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexImport
      parentRoute: typeof AuthenticatedEEstablishmentIdSServiceIdImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSuperAdminRouteChildren {
  AuthenticatedSuperAdminEstablishmentIdRoute: typeof AuthenticatedSuperAdminEstablishmentIdRoute
  AuthenticatedSuperAdminAccessLogRoute: typeof AuthenticatedSuperAdminAccessLogRoute
  AuthenticatedSuperAdminUsersRoute: typeof AuthenticatedSuperAdminUsersRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
}

const AuthenticatedSuperAdminRouteChildren: AuthenticatedSuperAdminRouteChildren =
  {
    AuthenticatedSuperAdminEstablishmentIdRoute:
      AuthenticatedSuperAdminEstablishmentIdRoute,
    AuthenticatedSuperAdminAccessLogRoute:
      AuthenticatedSuperAdminAccessLogRoute,
    AuthenticatedSuperAdminUsersRoute: AuthenticatedSuperAdminUsersRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
  }

const AuthenticatedSuperAdminRouteWithChildren =
  AuthenticatedSuperAdminRoute._addFileChildren(
    AuthenticatedSuperAdminRouteChildren,
  )

interface AuthenticatedEEstablishmentIdAdminRouteChildren {
  AuthenticatedEEstablishmentIdAdminActivityLogRoute: typeof AuthenticatedEEstablishmentIdAdminActivityLogRoute
  AuthenticatedEEstablishmentIdAdminGrantsRoute: typeof AuthenticatedEEstablishmentIdAdminGrantsRoute
  AuthenticatedEEstablishmentIdAdminLocationsRoute: typeof AuthenticatedEEstablishmentIdAdminLocationsRoute
  AuthenticatedEEstablishmentIdAdminMembersRoute: typeof AuthenticatedEEstablishmentIdAdminMembersRoute
  AuthenticatedEEstablishmentIdAdminServicesRoute: typeof AuthenticatedEEstablishmentIdAdminServicesRoute
  AuthenticatedEEstablishmentIdAdminSoignantsRoute: typeof AuthenticatedEEstablishmentIdAdminSoignantsRoute
}

const AuthenticatedEEstablishmentIdAdminRouteChildren: AuthenticatedEEstablishmentIdAdminRouteChildren =
  {
    AuthenticatedEEstablishmentIdAdminActivityLogRoute:
      AuthenticatedEEstablishmentIdAdminActivityLogRoute,
    AuthenticatedEEstablishmentIdAdminGrantsRoute:
      AuthenticatedEEstablishmentIdAdminGrantsRoute,
    AuthenticatedEEstablishmentIdAdminLocationsRoute:
      AuthenticatedEEstablishmentIdAdminLocationsRoute,
    AuthenticatedEEstablishmentIdAdminMembersRoute:
      AuthenticatedEEstablishmentIdAdminMembersRoute,
    AuthenticatedEEstablishmentIdAdminServicesRoute:
      AuthenticatedEEstablishmentIdAdminServicesRoute,
    AuthenticatedEEstablishmentIdAdminSoignantsRoute:
      AuthenticatedEEstablishmentIdAdminSoignantsRoute,
  }

const AuthenticatedEEstablishmentIdAdminRouteWithChildren =
  AuthenticatedEEstablishmentIdAdminRoute._addFileChildren(
    AuthenticatedEEstablishmentIdAdminRouteChildren,
  )

interface AuthenticatedEEstablishmentIdSServiceIdSettingsRouteChildren {
  AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateRoute
  AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningRoute
  AuthenticatedEEstablishmentIdSServiceIdSettingsThematicRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsThematicRoute
}

const AuthenticatedEEstablishmentIdSServiceIdSettingsRouteChildren: AuthenticatedEEstablishmentIdSServiceIdSettingsRouteChildren =
  {
    AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateRoute:
      AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateRoute,
    AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningRoute:
      AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningRoute,
    AuthenticatedEEstablishmentIdSServiceIdSettingsThematicRoute:
      AuthenticatedEEstablishmentIdSServiceIdSettingsThematicRoute,
  }

const AuthenticatedEEstablishmentIdSServiceIdSettingsRouteWithChildren =
  AuthenticatedEEstablishmentIdSServiceIdSettingsRoute._addFileChildren(
    AuthenticatedEEstablishmentIdSServiceIdSettingsRouteChildren,
  )

interface AuthenticatedEEstablishmentIdSServiceIdRouteChildren {
  AuthenticatedEEstablishmentIdSServiceIdSettingsRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSettingsRouteWithChildren
  AuthenticatedEEstablishmentIdSServiceIdActivityLogRoute: typeof AuthenticatedEEstablishmentIdSServiceIdActivityLogRoute
  AuthenticatedEEstablishmentIdSServiceIdAgendaRoute: typeof AuthenticatedEEstablishmentIdSServiceIdAgendaRoute
  AuthenticatedEEstablishmentIdSServiceIdDashboardRoute: typeof AuthenticatedEEstablishmentIdSServiceIdDashboardRoute
  AuthenticatedEEstablishmentIdSServiceIdLocationRoute: typeof AuthenticatedEEstablishmentIdSServiceIdLocationRoute
  AuthenticatedEEstablishmentIdSServiceIdSoignantRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSoignantRoute
  AuthenticatedEEstablishmentIdSServiceIdSuiviRoute: typeof AuthenticatedEEstablishmentIdSServiceIdSuiviRoute
  AuthenticatedEEstablishmentIdSServiceIdIndexRoute: typeof AuthenticatedEEstablishmentIdSServiceIdIndexRoute
  AuthenticatedEEstablishmentIdSServiceIdPatientIndexRoute: typeof AuthenticatedEEstablishmentIdSServiceIdPatientIndexRoute
  AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesRoute: typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesRoute
  AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexRoute: typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexRoute
}

const AuthenticatedEEstablishmentIdSServiceIdRouteChildren: AuthenticatedEEstablishmentIdSServiceIdRouteChildren =
  {
    AuthenticatedEEstablishmentIdSServiceIdSettingsRoute:
      AuthenticatedEEstablishmentIdSServiceIdSettingsRouteWithChildren,
    AuthenticatedEEstablishmentIdSServiceIdActivityLogRoute:
      AuthenticatedEEstablishmentIdSServiceIdActivityLogRoute,
    AuthenticatedEEstablishmentIdSServiceIdAgendaRoute:
      AuthenticatedEEstablishmentIdSServiceIdAgendaRoute,
    AuthenticatedEEstablishmentIdSServiceIdDashboardRoute:
      AuthenticatedEEstablishmentIdSServiceIdDashboardRoute,
    AuthenticatedEEstablishmentIdSServiceIdLocationRoute:
      AuthenticatedEEstablishmentIdSServiceIdLocationRoute,
    AuthenticatedEEstablishmentIdSServiceIdSoignantRoute:
      AuthenticatedEEstablishmentIdSServiceIdSoignantRoute,
    AuthenticatedEEstablishmentIdSServiceIdSuiviRoute:
      AuthenticatedEEstablishmentIdSServiceIdSuiviRoute,
    AuthenticatedEEstablishmentIdSServiceIdIndexRoute:
      AuthenticatedEEstablishmentIdSServiceIdIndexRoute,
    AuthenticatedEEstablishmentIdSServiceIdPatientIndexRoute:
      AuthenticatedEEstablishmentIdSServiceIdPatientIndexRoute,
    AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesRoute:
      AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesRoute,
    AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexRoute:
      AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexRoute,
  }

const AuthenticatedEEstablishmentIdSServiceIdRouteWithChildren =
  AuthenticatedEEstablishmentIdSServiceIdRoute._addFileChildren(
    AuthenticatedEEstablishmentIdSServiceIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedChooseContextRoute: typeof AuthenticatedChooseContextRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSuiviRoute: typeof AuthenticatedSuiviRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPatientPatientIDRoute: typeof AuthenticatedPatientPatientIDRoute
  AuthenticatedSettingsActivityLogRoute: typeof AuthenticatedSettingsActivityLogRoute
  AuthenticatedSettingsDiagnosticTemplateRoute: typeof AuthenticatedSettingsDiagnosticTemplateRoute
  AuthenticatedSettingsLocationRoute: typeof AuthenticatedSettingsLocationRoute
  AuthenticatedSettingsPlanningRoute: typeof AuthenticatedSettingsPlanningRoute
  AuthenticatedSettingsSoignantRoute: typeof AuthenticatedSettingsSoignantRoute
  AuthenticatedSettingsThematicRoute: typeof AuthenticatedSettingsThematicRoute
  AuthenticatedSettingsUserRoute: typeof AuthenticatedSettingsUserRoute
  AuthenticatedUserSettingsRoute: typeof AuthenticatedUserSettingsRoute
  AuthenticatedPatientIndexRoute: typeof AuthenticatedPatientIndexRoute
  AuthenticatedEEstablishmentIdAdminRoute: typeof AuthenticatedEEstablishmentIdAdminRouteWithChildren
  AuthenticatedEEstablishmentIdSServiceIdRoute: typeof AuthenticatedEEstablishmentIdSServiceIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedChooseContextRoute: AuthenticatedChooseContextRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSuiviRoute: AuthenticatedSuiviRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPatientPatientIDRoute: AuthenticatedPatientPatientIDRoute,
  AuthenticatedSettingsActivityLogRoute: AuthenticatedSettingsActivityLogRoute,
  AuthenticatedSettingsDiagnosticTemplateRoute:
    AuthenticatedSettingsDiagnosticTemplateRoute,
  AuthenticatedSettingsLocationRoute: AuthenticatedSettingsLocationRoute,
  AuthenticatedSettingsPlanningRoute: AuthenticatedSettingsPlanningRoute,
  AuthenticatedSettingsSoignantRoute: AuthenticatedSettingsSoignantRoute,
  AuthenticatedSettingsThematicRoute: AuthenticatedSettingsThematicRoute,
  AuthenticatedSettingsUserRoute: AuthenticatedSettingsUserRoute,
  AuthenticatedUserSettingsRoute: AuthenticatedUserSettingsRoute,
  AuthenticatedPatientIndexRoute: AuthenticatedPatientIndexRoute,
  AuthenticatedEEstablishmentIdAdminRoute:
    AuthenticatedEEstablishmentIdAdminRouteWithChildren,
  AuthenticatedEEstablishmentIdSServiceIdRoute:
    AuthenticatedEEstablishmentIdSServiceIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteWithChildren
  '/pending': typeof PendingRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/choose-context': typeof AuthenticatedChooseContextRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/suivi': typeof AuthenticatedSuiviRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/auth/access-link': typeof AuthAccessLinkRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/patient/$patientID': typeof AuthenticatedPatientPatientIDRoute
  '/settings/activity-log': typeof AuthenticatedSettingsActivityLogRoute
  '/settings/diagnostic-template': typeof AuthenticatedSettingsDiagnosticTemplateRoute
  '/settings/location': typeof AuthenticatedSettingsLocationRoute
  '/settings/planning': typeof AuthenticatedSettingsPlanningRoute
  '/settings/soignant': typeof AuthenticatedSettingsSoignantRoute
  '/settings/thematic': typeof AuthenticatedSettingsThematicRoute
  '/settings/user': typeof AuthenticatedSettingsUserRoute
  '/super-admin/$establishmentId': typeof AuthenticatedSuperAdminEstablishmentIdRoute
  '/super-admin/access-log': typeof AuthenticatedSuperAdminAccessLogRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/user/settings': typeof AuthenticatedUserSettingsRoute
  '/patient': typeof AuthenticatedPatientIndexRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/e/$establishmentId/admin': typeof AuthenticatedEEstablishmentIdAdminRouteWithChildren
  '/e/$establishmentId/admin/activity-log': typeof AuthenticatedEEstablishmentIdAdminActivityLogRoute
  '/e/$establishmentId/admin/grants': typeof AuthenticatedEEstablishmentIdAdminGrantsRoute
  '/e/$establishmentId/admin/locations': typeof AuthenticatedEEstablishmentIdAdminLocationsRoute
  '/e/$establishmentId/admin/members': typeof AuthenticatedEEstablishmentIdAdminMembersRoute
  '/e/$establishmentId/admin/services': typeof AuthenticatedEEstablishmentIdAdminServicesRoute
  '/e/$establishmentId/admin/soignants': typeof AuthenticatedEEstablishmentIdAdminSoignantsRoute
  '/e/$establishmentId/s/$serviceId': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsRouteWithChildren
  '/e/$establishmentId/s/$serviceId/activity-log': typeof AuthenticatedEEstablishmentIdSServiceIdActivityLogRoute
  '/e/$establishmentId/s/$serviceId/agenda': typeof AuthenticatedEEstablishmentIdSServiceIdAgendaRoute
  '/e/$establishmentId/s/$serviceId/dashboard': typeof AuthenticatedEEstablishmentIdSServiceIdDashboardRoute
  '/e/$establishmentId/s/$serviceId/location': typeof AuthenticatedEEstablishmentIdSServiceIdLocationRoute
  '/e/$establishmentId/s/$serviceId/soignant': typeof AuthenticatedEEstablishmentIdSServiceIdSoignantRoute
  '/e/$establishmentId/s/$serviceId/suivi': typeof AuthenticatedEEstablishmentIdSServiceIdSuiviRoute
  '/e/$establishmentId/s/$serviceId/': typeof AuthenticatedEEstablishmentIdSServiceIdIndexRoute
  '/e/$establishmentId/s/$serviceId/diagnostic-template': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateRoute
  '/e/$establishmentId/s/$serviceId/planning': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningRoute
  '/e/$establishmentId/s/$serviceId/thematic': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsThematicRoute
  '/e/$establishmentId/s/$serviceId/patient': typeof AuthenticatedEEstablishmentIdSServiceIdPatientIndexRoute
  '/e/$establishmentId/s/$serviceId/patient/$patientID/acces': typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesRoute
  '/e/$establishmentId/s/$serviceId/patient/$patientID': typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexRoute
}

export interface FileRoutesByTo {
  '/pending': typeof PendingRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/choose-context': typeof AuthenticatedChooseContextRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/suivi': typeof AuthenticatedSuiviRoute
  '/auth/access-link': typeof AuthAccessLinkRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/patient/$patientID': typeof AuthenticatedPatientPatientIDRoute
  '/settings/activity-log': typeof AuthenticatedSettingsActivityLogRoute
  '/settings/diagnostic-template': typeof AuthenticatedSettingsDiagnosticTemplateRoute
  '/settings/location': typeof AuthenticatedSettingsLocationRoute
  '/settings/planning': typeof AuthenticatedSettingsPlanningRoute
  '/settings/soignant': typeof AuthenticatedSettingsSoignantRoute
  '/settings/thematic': typeof AuthenticatedSettingsThematicRoute
  '/settings/user': typeof AuthenticatedSettingsUserRoute
  '/super-admin/$establishmentId': typeof AuthenticatedSuperAdminEstablishmentIdRoute
  '/super-admin/access-log': typeof AuthenticatedSuperAdminAccessLogRoute
  '/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/user/settings': typeof AuthenticatedUserSettingsRoute
  '/patient': typeof AuthenticatedPatientIndexRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
  '/e/$establishmentId/admin': typeof AuthenticatedEEstablishmentIdAdminRouteWithChildren
  '/e/$establishmentId/admin/activity-log': typeof AuthenticatedEEstablishmentIdAdminActivityLogRoute
  '/e/$establishmentId/admin/grants': typeof AuthenticatedEEstablishmentIdAdminGrantsRoute
  '/e/$establishmentId/admin/locations': typeof AuthenticatedEEstablishmentIdAdminLocationsRoute
  '/e/$establishmentId/admin/members': typeof AuthenticatedEEstablishmentIdAdminMembersRoute
  '/e/$establishmentId/admin/services': typeof AuthenticatedEEstablishmentIdAdminServicesRoute
  '/e/$establishmentId/admin/soignants': typeof AuthenticatedEEstablishmentIdAdminSoignantsRoute
  '/e/$establishmentId/s/$serviceId': typeof AuthenticatedEEstablishmentIdSServiceIdIndexRoute
  '/e/$establishmentId/s/$serviceId/activity-log': typeof AuthenticatedEEstablishmentIdSServiceIdActivityLogRoute
  '/e/$establishmentId/s/$serviceId/agenda': typeof AuthenticatedEEstablishmentIdSServiceIdAgendaRoute
  '/e/$establishmentId/s/$serviceId/dashboard': typeof AuthenticatedEEstablishmentIdSServiceIdDashboardRoute
  '/e/$establishmentId/s/$serviceId/location': typeof AuthenticatedEEstablishmentIdSServiceIdLocationRoute
  '/e/$establishmentId/s/$serviceId/soignant': typeof AuthenticatedEEstablishmentIdSServiceIdSoignantRoute
  '/e/$establishmentId/s/$serviceId/suivi': typeof AuthenticatedEEstablishmentIdSServiceIdSuiviRoute
  '/e/$establishmentId/s/$serviceId/diagnostic-template': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateRoute
  '/e/$establishmentId/s/$serviceId/planning': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningRoute
  '/e/$establishmentId/s/$serviceId/thematic': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsThematicRoute
  '/e/$establishmentId/s/$serviceId/patient': typeof AuthenticatedEEstablishmentIdSServiceIdPatientIndexRoute
  '/e/$establishmentId/s/$serviceId/patient/$patientID/acces': typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesRoute
  '/e/$establishmentId/s/$serviceId/patient/$patientID': typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/pending': typeof PendingRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/choose-context': typeof AuthenticatedChooseContextRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/suivi': typeof AuthenticatedSuiviRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/auth/access-link': typeof AuthAccessLinkRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/patient/$patientID': typeof AuthenticatedPatientPatientIDRoute
  '/_authenticated/settings/activity-log': typeof AuthenticatedSettingsActivityLogRoute
  '/_authenticated/settings/diagnostic-template': typeof AuthenticatedSettingsDiagnosticTemplateRoute
  '/_authenticated/settings/location': typeof AuthenticatedSettingsLocationRoute
  '/_authenticated/settings/planning': typeof AuthenticatedSettingsPlanningRoute
  '/_authenticated/settings/soignant': typeof AuthenticatedSettingsSoignantRoute
  '/_authenticated/settings/thematic': typeof AuthenticatedSettingsThematicRoute
  '/_authenticated/settings/user': typeof AuthenticatedSettingsUserRoute
  '/_authenticated/super-admin/$establishmentId': typeof AuthenticatedSuperAdminEstablishmentIdRoute
  '/_authenticated/super-admin/access-log': typeof AuthenticatedSuperAdminAccessLogRoute
  '/_authenticated/super-admin/users': typeof AuthenticatedSuperAdminUsersRoute
  '/_authenticated/user/settings': typeof AuthenticatedUserSettingsRoute
  '/_authenticated/patient/': typeof AuthenticatedPatientIndexRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
  '/_authenticated/e/$establishmentId/admin': typeof AuthenticatedEEstablishmentIdAdminRouteWithChildren
  '/_authenticated/e/$establishmentId/admin/activity-log': typeof AuthenticatedEEstablishmentIdAdminActivityLogRoute
  '/_authenticated/e/$establishmentId/admin/grants': typeof AuthenticatedEEstablishmentIdAdminGrantsRoute
  '/_authenticated/e/$establishmentId/admin/locations': typeof AuthenticatedEEstablishmentIdAdminLocationsRoute
  '/_authenticated/e/$establishmentId/admin/members': typeof AuthenticatedEEstablishmentIdAdminMembersRoute
  '/_authenticated/e/$establishmentId/admin/services': typeof AuthenticatedEEstablishmentIdAdminServicesRoute
  '/_authenticated/e/$establishmentId/admin/soignants': typeof AuthenticatedEEstablishmentIdAdminSoignantsRoute
  '/_authenticated/e/$establishmentId/s/$serviceId': typeof AuthenticatedEEstablishmentIdSServiceIdRouteWithChildren
  '/_authenticated/e/$establishmentId/s/$serviceId/_settings': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsRouteWithChildren
  '/_authenticated/e/$establishmentId/s/$serviceId/activity-log': typeof AuthenticatedEEstablishmentIdSServiceIdActivityLogRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/agenda': typeof AuthenticatedEEstablishmentIdSServiceIdAgendaRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/dashboard': typeof AuthenticatedEEstablishmentIdSServiceIdDashboardRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/location': typeof AuthenticatedEEstablishmentIdSServiceIdLocationRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/soignant': typeof AuthenticatedEEstablishmentIdSServiceIdSoignantRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/suivi': typeof AuthenticatedEEstablishmentIdSServiceIdSuiviRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/': typeof AuthenticatedEEstablishmentIdSServiceIdIndexRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/_settings/diagnostic-template': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsDiagnosticTemplateRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/_settings/planning': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsPlanningRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/_settings/thematic': typeof AuthenticatedEEstablishmentIdSServiceIdSettingsThematicRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/patient/': typeof AuthenticatedEEstablishmentIdSServiceIdPatientIndexRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/acces': typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDAccesRoute
  '/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/': typeof AuthenticatedEEstablishmentIdSServiceIdPatientPatientIDIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/pending'
    | '/agenda'
    | '/choose-context'
    | '/dashboard'
    | '/suivi'
    | '/super-admin'
    | '/auth/access-link'
    | '/'
    | '/auth'
    | '/patient/$patientID'
    | '/settings/activity-log'
    | '/settings/diagnostic-template'
    | '/settings/location'
    | '/settings/planning'
    | '/settings/soignant'
    | '/settings/thematic'
    | '/settings/user'
    | '/super-admin/$establishmentId'
    | '/super-admin/access-log'
    | '/super-admin/users'
    | '/user/settings'
    | '/patient'
    | '/super-admin/'
    | '/e/$establishmentId/admin'
    | '/e/$establishmentId/admin/activity-log'
    | '/e/$establishmentId/admin/grants'
    | '/e/$establishmentId/admin/locations'
    | '/e/$establishmentId/admin/members'
    | '/e/$establishmentId/admin/services'
    | '/e/$establishmentId/admin/soignants'
    | '/e/$establishmentId/s/$serviceId'
    | '/e/$establishmentId/s/$serviceId/activity-log'
    | '/e/$establishmentId/s/$serviceId/agenda'
    | '/e/$establishmentId/s/$serviceId/dashboard'
    | '/e/$establishmentId/s/$serviceId/location'
    | '/e/$establishmentId/s/$serviceId/soignant'
    | '/e/$establishmentId/s/$serviceId/suivi'
    | '/e/$establishmentId/s/$serviceId/'
    | '/e/$establishmentId/s/$serviceId/diagnostic-template'
    | '/e/$establishmentId/s/$serviceId/planning'
    | '/e/$establishmentId/s/$serviceId/thematic'
    | '/e/$establishmentId/s/$serviceId/patient'
    | '/e/$establishmentId/s/$serviceId/patient/$patientID/acces'
    | '/e/$establishmentId/s/$serviceId/patient/$patientID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pending'
    | '/agenda'
    | '/choose-context'
    | '/dashboard'
    | '/suivi'
    | '/auth/access-link'
    | '/'
    | '/auth'
    | '/patient/$patientID'
    | '/settings/activity-log'
    | '/settings/diagnostic-template'
    | '/settings/location'
    | '/settings/planning'
    | '/settings/soignant'
    | '/settings/thematic'
    | '/settings/user'
    | '/super-admin/$establishmentId'
    | '/super-admin/access-log'
    | '/super-admin/users'
    | '/user/settings'
    | '/patient'
    | '/super-admin'
    | '/e/$establishmentId/admin'
    | '/e/$establishmentId/admin/activity-log'
    | '/e/$establishmentId/admin/grants'
    | '/e/$establishmentId/admin/locations'
    | '/e/$establishmentId/admin/members'
    | '/e/$establishmentId/admin/services'
    | '/e/$establishmentId/admin/soignants'
    | '/e/$establishmentId/s/$serviceId'
    | '/e/$establishmentId/s/$serviceId/activity-log'
    | '/e/$establishmentId/s/$serviceId/agenda'
    | '/e/$establishmentId/s/$serviceId/dashboard'
    | '/e/$establishmentId/s/$serviceId/location'
    | '/e/$establishmentId/s/$serviceId/soignant'
    | '/e/$establishmentId/s/$serviceId/suivi'
    | '/e/$establishmentId/s/$serviceId/diagnostic-template'
    | '/e/$establishmentId/s/$serviceId/planning'
    | '/e/$establishmentId/s/$serviceId/thematic'
    | '/e/$establishmentId/s/$serviceId/patient'
    | '/e/$establishmentId/s/$serviceId/patient/$patientID/acces'
    | '/e/$establishmentId/s/$serviceId/patient/$patientID'
  id:
    | '__root__'
    | '/_authenticated'
    | '/pending'
    | '/_authenticated/agenda'
    | '/_authenticated/choose-context'
    | '/_authenticated/dashboard'
    | '/_authenticated/suivi'
    | '/_authenticated/super-admin'
    | '/auth/access-link'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/patient/$patientID'
    | '/_authenticated/settings/activity-log'
    | '/_authenticated/settings/diagnostic-template'
    | '/_authenticated/settings/location'
    | '/_authenticated/settings/planning'
    | '/_authenticated/settings/soignant'
    | '/_authenticated/settings/thematic'
    | '/_authenticated/settings/user'
    | '/_authenticated/super-admin/$establishmentId'
    | '/_authenticated/super-admin/access-log'
    | '/_authenticated/super-admin/users'
    | '/_authenticated/user/settings'
    | '/_authenticated/patient/'
    | '/_authenticated/super-admin/'
    | '/_authenticated/e/$establishmentId/admin'
    | '/_authenticated/e/$establishmentId/admin/activity-log'
    | '/_authenticated/e/$establishmentId/admin/grants'
    | '/_authenticated/e/$establishmentId/admin/locations'
    | '/_authenticated/e/$establishmentId/admin/members'
    | '/_authenticated/e/$establishmentId/admin/services'
    | '/_authenticated/e/$establishmentId/admin/soignants'
    | '/_authenticated/e/$establishmentId/s/$serviceId'
    | '/_authenticated/e/$establishmentId/s/$serviceId/_settings'
    | '/_authenticated/e/$establishmentId/s/$serviceId/activity-log'
    | '/_authenticated/e/$establishmentId/s/$serviceId/agenda'
    | '/_authenticated/e/$establishmentId/s/$serviceId/dashboard'
    | '/_authenticated/e/$establishmentId/s/$serviceId/location'
    | '/_authenticated/e/$establishmentId/s/$serviceId/soignant'
    | '/_authenticated/e/$establishmentId/s/$serviceId/suivi'
    | '/_authenticated/e/$establishmentId/s/$serviceId/'
    | '/_authenticated/e/$establishmentId/s/$serviceId/_settings/diagnostic-template'
    | '/_authenticated/e/$establishmentId/s/$serviceId/_settings/planning'
    | '/_authenticated/e/$establishmentId/s/$serviceId/_settings/thematic'
    | '/_authenticated/e/$establishmentId/s/$serviceId/patient/'
    | '/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/acces'
    | '/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PendingRoute: typeof PendingRoute
  AuthAccessLinkRoute: typeof AuthAccessLinkRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PendingRoute: PendingRoute,
  AuthAccessLinkRoute: AuthAccessLinkRoute,
  AuthIndexRoute: AuthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/pending",
        "/auth/access-link",
        "/auth/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/agenda",
        "/_authenticated/choose-context",
        "/_authenticated/dashboard",
        "/_authenticated/suivi",
        "/_authenticated/super-admin",
        "/_authenticated/",
        "/_authenticated/patient/$patientID",
        "/_authenticated/settings/activity-log",
        "/_authenticated/settings/diagnostic-template",
        "/_authenticated/settings/location",
        "/_authenticated/settings/planning",
        "/_authenticated/settings/soignant",
        "/_authenticated/settings/thematic",
        "/_authenticated/settings/user",
        "/_authenticated/user/settings",
        "/_authenticated/patient/",
        "/_authenticated/e/$establishmentId/admin",
        "/_authenticated/e/$establishmentId/s/$serviceId"
      ]
    },
    "/pending": {
      "filePath": "pending.tsx"
    },
    "/_authenticated/agenda": {
      "filePath": "_authenticated/agenda.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/choose-context": {
      "filePath": "_authenticated/choose-context.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/suivi": {
      "filePath": "_authenticated/suivi.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/super-admin": {
      "filePath": "_authenticated/super-admin.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/super-admin/$establishmentId",
        "/_authenticated/super-admin/access-log",
        "/_authenticated/super-admin/users",
        "/_authenticated/super-admin/"
      ]
    },
    "/auth/access-link": {
      "filePath": "auth/access-link.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/_authenticated/patient/$patientID": {
      "filePath": "_authenticated/patient/$patientID.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/activity-log": {
      "filePath": "_authenticated/settings/activity-log.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/diagnostic-template": {
      "filePath": "_authenticated/settings/diagnostic-template.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/location": {
      "filePath": "_authenticated/settings/location.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/planning": {
      "filePath": "_authenticated/settings/planning.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/soignant": {
      "filePath": "_authenticated/settings/soignant.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/thematic": {
      "filePath": "_authenticated/settings/thematic.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/user": {
      "filePath": "_authenticated/settings/user.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/super-admin/$establishmentId": {
      "filePath": "_authenticated/super-admin/$establishmentId.tsx",
      "parent": "/_authenticated/super-admin"
    },
    "/_authenticated/super-admin/access-log": {
      "filePath": "_authenticated/super-admin/access-log.tsx",
      "parent": "/_authenticated/super-admin"
    },
    "/_authenticated/super-admin/users": {
      "filePath": "_authenticated/super-admin/users.tsx",
      "parent": "/_authenticated/super-admin"
    },
    "/_authenticated/user/settings": {
      "filePath": "_authenticated/user/settings.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/patient/": {
      "filePath": "_authenticated/patient/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/super-admin/": {
      "filePath": "_authenticated/super-admin/index.tsx",
      "parent": "/_authenticated/super-admin"
    },
    "/_authenticated/e/$establishmentId/admin": {
      "filePath": "_authenticated/e/$establishmentId/admin.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/e/$establishmentId/admin/activity-log",
        "/_authenticated/e/$establishmentId/admin/grants",
        "/_authenticated/e/$establishmentId/admin/locations",
        "/_authenticated/e/$establishmentId/admin/members",
        "/_authenticated/e/$establishmentId/admin/services",
        "/_authenticated/e/$establishmentId/admin/soignants"
      ]
    },
    "/_authenticated/e/$establishmentId/admin/activity-log": {
      "filePath": "_authenticated/e/$establishmentId/admin/activity-log.tsx",
      "parent": "/_authenticated/e/$establishmentId/admin"
    },
    "/_authenticated/e/$establishmentId/admin/grants": {
      "filePath": "_authenticated/e/$establishmentId/admin/grants.tsx",
      "parent": "/_authenticated/e/$establishmentId/admin"
    },
    "/_authenticated/e/$establishmentId/admin/locations": {
      "filePath": "_authenticated/e/$establishmentId/admin/locations.tsx",
      "parent": "/_authenticated/e/$establishmentId/admin"
    },
    "/_authenticated/e/$establishmentId/admin/members": {
      "filePath": "_authenticated/e/$establishmentId/admin/members.tsx",
      "parent": "/_authenticated/e/$establishmentId/admin"
    },
    "/_authenticated/e/$establishmentId/admin/services": {
      "filePath": "_authenticated/e/$establishmentId/admin/services.tsx",
      "parent": "/_authenticated/e/$establishmentId/admin"
    },
    "/_authenticated/e/$establishmentId/admin/soignants": {
      "filePath": "_authenticated/e/$establishmentId/admin/soignants.tsx",
      "parent": "/_authenticated/e/$establishmentId/admin"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/e/$establishmentId/s/$serviceId/_settings",
        "/_authenticated/e/$establishmentId/s/$serviceId/activity-log",
        "/_authenticated/e/$establishmentId/s/$serviceId/agenda",
        "/_authenticated/e/$establishmentId/s/$serviceId/dashboard",
        "/_authenticated/e/$establishmentId/s/$serviceId/location",
        "/_authenticated/e/$establishmentId/s/$serviceId/soignant",
        "/_authenticated/e/$establishmentId/s/$serviceId/suivi",
        "/_authenticated/e/$establishmentId/s/$serviceId/",
        "/_authenticated/e/$establishmentId/s/$serviceId/patient/",
        "/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/acces",
        "/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/"
      ]
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/_settings": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/_settings.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId",
      "children": [
        "/_authenticated/e/$establishmentId/s/$serviceId/_settings/diagnostic-template",
        "/_authenticated/e/$establishmentId/s/$serviceId/_settings/planning",
        "/_authenticated/e/$establishmentId/s/$serviceId/_settings/thematic"
      ]
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/activity-log": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/activity-log.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/agenda": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/agenda.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/dashboard": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/dashboard.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/location": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/location.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/soignant": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/soignant.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/suivi": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/suivi.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/index.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/_settings/diagnostic-template": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/_settings/diagnostic-template.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId/_settings"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/_settings/planning": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/_settings/planning.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId/_settings"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/_settings/thematic": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/_settings/thematic.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId/_settings"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/patient/": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/patient/index.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/acces": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/acces.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    },
    "/_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/": {
      "filePath": "_authenticated/e/$establishmentId/s/$serviceId/patient/$patientID/index.tsx",
      "parent": "/_authenticated/e/$establishmentId/s/$serviceId"
    }
  }
}
ROUTE_MANIFEST_END */
